### ISSUE TITLE
Add banner & link to user manual into README

### ISSUE THREAD

**Issue by ghost** [glukfonts/SVGinOTlayersCompositor#2]
> - https://twitter.com/glukfonts/status/1179074431790059525

- [x] Add original banner (PNG) as - https://github.com/glukfonts/SVGinOTlayersCompositor/blob/master/doc/svginot-banner.png
- [x] Insert banner & link to user manual into `README.md`

```
# SVGinOT layers Compositor

python 2.x script for FontForge. My first SVGinOpenType color fonts generator. Hope, will work...

- [User Manual](https://github.com/glukfonts/SVGinOTlayersCompositor/raw/master/doc/howto.pdf) (PDF)

[SVGinOT banner](doc/svginot-banner.png)

...
```

**Comment by glukfonts** [comment]
- svginot_banner.png and svginot_banner_800.png (800px width) added to doc/
- added link to pdf in README.md
